import Head from 'next/head';
import Hero from '@/components/Hero';
import Articles from '@/components/Articles';
import useArticlesContext from '@/hooks/useArticlesContext';

export default function Home() {
    const { articles } = useArticlesContext() ?? {};

    return (
        <>
            <Head>
                <title>Stock Off The Press</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Hero />
                <div className="w-full flex justify-center bg-zinc-800">
                    <div className="m-6">
                        <Articles articles={articles ?? []} />
                    </div>
                </div>
            </main>
        </>
    );
}
