import Head from 'next/head';
import Hero from '@/components/Hero';
import useArticlesContext from '@/hooks/useArticlesContext';

export default function Home() {
    const { articles } = useArticlesContext() || {};
    
    return (
        <>
            <Head>
                <title>Stock Off The Press</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Hero />
                <div>
                    {JSON.stringify(articles)}
                </div>
            </main>
        </>
    );
}
